<?php

namespace DropyBundle\Entity;

/**
 * CollectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionsRepository extends \Doctrine\ORM\EntityRepository
{
}
